# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ea4d690bbfb086784b1d86adb758b9b3b3eb9e2e0bec599ce9e3ea67657f52eeb778c59b2a4eead06b2f4f901b0751fbc7ee1bac437a7a92a0f8524517f2dba8

test:
  secret_key_base: 0de1b2e4a2ad54952aa8ea0dfa32bb959955d40dc005ca220c7f007eb4e2fc1ada876b217bf0c2cff47543a417dc884235db5d56bcf90ce74a96e66f767fa1b5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
